[package]
name = "string_builder_demo"
version = "0.1.0"

[build]
backend = "c"
default_target = "x86_64-apple-darwin"

[build.entries]
demo = "demo.gecko"

[build.profiles.debug]
optimize = false

[build.profiles.release]
optimize = true
