// spec: spec/types.md, spec/functions.md, spec/classes.md, spec/traits.md, spec/generics.md, spec/control-flow.md, spec/operators.md, spec/pointers.md, spec/memory.md, spec/c-interop.md, spec/attributes.md

package backends

import (
	"strings"

	cbackend "github.com/neutrino2211/gecko/backends/c_backend"
)

// generateCCode creates the final C source code from scope information.
func generateCCode(info *cbackend.CScopeInformation, treeshakeEnabled bool) string {
	if treeshakeEnabled {
		pruneUnreachableCFunctions(info)
	}

	var sb strings.Builder

	// Header comment
	sb.WriteString("/* Generated by Gecko C Backend */\n\n")

	// Include standard headers
	sb.WriteString("#include <stdint.h>\n")
	sb.WriteString("#include <stddef.h>\n")

	// Write user-specified includes from cimport statements
	if len(info.Includes) > 0 {
		for _, include := range info.Includes {
			sb.WriteString(include)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\n")

	// Gecko runtime hooks used by lowered try diagnostics.
	sb.WriteString("/* Gecko runtime hooks */\n")
	sb.WriteString("typedef void (*__gecko_try_error_handler_t)(const char* file, int32_t line, int32_t column, const char* function_name, const char* expr);\n")
	sb.WriteString("static __gecko_try_error_handler_t __gecko_try_error_handler = 0;\n")
	sb.WriteString("void __gecko_set_try_error_handler(__gecko_try_error_handler_t handler) {\n")
	sb.WriteString("    __gecko_try_error_handler = handler;\n")
	sb.WriteString("}\n")
	sb.WriteString("static void __gecko_try_fail(const char* file, int32_t line, int32_t column, const char* function_name, const char* expr) {\n")
	sb.WriteString("    if (__gecko_try_error_handler) {\n")
	sb.WriteString("        __gecko_try_error_handler(file, line, column, function_name, expr);\n")
	sb.WriteString("    }\n")
	sb.WriteString("    __builtin_trap();\n")
	sb.WriteString("}\n\n")

	// Write typedef declarations (external types)
	if len(info.TypeDefs) > 0 {
		sb.WriteString("/* External type declarations */\n")
		for _, typeDef := range info.TypeDefs {
			sb.WriteString(typeDef)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Write type definitions (structs) - use StructDefs if available (sorted), else Types
	if len(info.StructDefs) > 0 {
		sb.WriteString("/* Type definitions */\n")
		for _, structDef := range info.StructDefs {
			sb.WriteString(structDef.Code)
			sb.WriteString("\n")
		}
	} else if len(info.Types) > 0 {
		sb.WriteString("/* Type definitions */\n")
		for _, typeDef := range info.Types {
			sb.WriteString(typeDef)
			sb.WriteString("\n")
		}
	}

	// Write extern declarations
	if len(info.Declarations) > 0 {
		sb.WriteString("/* External declarations */\n")
		for _, decl := range info.Declarations {
			sb.WriteString(decl)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Write global variables
	if len(info.Globals) > 0 {
		sb.WriteString("/* Global variables */\n")
		for _, global := range info.Globals {
			sb.WriteString(global)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Write function definitions
	if len(info.Functions) > 0 {
		sb.WriteString("/* Function definitions */\n")
		for _, fn := range info.Functions {
			sb.WriteString(fn)
			sb.WriteString("\n")
		}
	}

	// Keep Gecko `external func` definitions alive under section GC.
	if treeshakeEnabled && len(info.ExternalRootSymbols) > 0 {
		sb.WriteString("/* Treeshake roots for Gecko external functions */\n")
		sb.WriteString("static void (* const __gecko_external_roots[])(void) __attribute__((used)) = {\n")
		for _, symbol := range info.ExternalRootSymbols {
			sb.WriteString("    (void (*)(void))" + symbol + ",\n")
		}
		sb.WriteString("};\n\n")
		sb.WriteString("/* Ensure external roots remain reachable when linker GC is enabled. */\n")
		sb.WriteString("static void __attribute__((constructor)) __gecko_keep_external_roots(void) {\n")
		sb.WriteString("    volatile const void* root = (const void*)__gecko_external_roots;\n")
		sb.WriteString("    (void)root;\n")
		sb.WriteString("}\n\n")
	}

	return sb.String()
}
