[package]
name = "GNote"
version = "0.1.0"

[build]
backend = "c"

[build.native]
headers = ["sqlite3.h", "webview/api.h"]
include_dirs = ["vendor/sqlite", "vendor/webview/core/include"]
objects = [".gecko_build/vendor/sqlite3.o", ".gecko_build/vendor/webview.o"]
ldflags = ["-framework", "WebKit", "-framework", "Cocoa", "-lc++", "-ldl"]

[build.entries]
main = "src/main.gecko"

[build.scripts]
pre_build = ["sh scripts/build_vendor.sh"]

[build.profiles.debug]
optimize = false

[build.profiles.release]
optimize = true
