/* Generated by Gecko C Backend */

#include <stdint.h>

/* Global variables */
const int64_t vga__WIDTH = 80;
const int64_t vga__HEIGHT = 25;
const uint64_t vga__ADDRESS = 0xB8000;
const uint8_t vga__BLACK = 0;
const uint8_t vga__BLUE = 1;
const uint8_t vga__GREEN = 2;
const uint8_t vga__CYAN = 3;
const uint8_t vga__RED = 4;
const uint8_t vga__MAGENTA = 5;
const uint8_t vga__BROWN = 6;
const uint8_t vga__LIGHT_GRAY = 7;
const uint8_t vga__DARK_GRAY = 8;
const uint8_t vga__LIGHT_BLUE = 9;
const uint8_t vga__LIGHT_GREEN = 10;
const uint8_t vga__LIGHT_CYAN = 11;
const uint8_t vga__LIGHT_RED = 12;
const uint8_t vga__LIGHT_MAGENTA = 13;
const uint8_t vga__YELLOW = 14;
const uint8_t vga__WHITE = 15;

/* Function definitions */
void cpu__halt() {
    __asm__ volatile ("hlt");
    return;
}

void cpu__disable_interrupts() {
    __asm__ volatile ("cli");
    return;
}

void cpu__enable_interrupts() {
    __asm__ volatile ("sti");
    return;
}

__attribute__((noreturn)) void cpu__hang() {
    cpu__disable_interrupts();
    cpu__halt();
    cpu__halt();
}

uint8_t vga__color(uint8_t fg, uint8_t bg) {
    return fg | (bg << 4);
}

uint16_t vga__entry(uint8_t c, uint8_t color) {
    return ((uint16_t)(c)) | (((uint16_t)(color)) << 8);
}

void vga__putchar(uint8_t c, uint8_t color, int64_t x, int64_t y) {
    volatile uint16_t* buffer = ((volatile uint16_t*)(vga__ADDRESS));
    int64_t index = y * vga__WIDTH + x;
    buffer[index] = vga__entry(c, color);
    return;
}

void vga__clear(uint8_t color) {
    volatile uint16_t* buffer = ((volatile uint16_t*)(vga__ADDRESS));
    uint16_t space = vga__entry(32, color);
    int64_t i = 0;
    while (i < 2000) {
    buffer[i] = space;
    i = i + 1;
    }
    return;
}

void vga__print(uint8_t* text, int64_t len, int64_t x, int64_t y, uint8_t color) {
    int64_t i = 0;
    while (i < len) {
    vga__putchar(text[i], color, x + i, y);
    i = i + 1;
    }
    return;
}

void kernel__write_hello(int64_t x, int64_t y, uint8_t color) {
    vga__putchar(72, color, x, y);
    vga__putchar(101, color, x + 1, y);
    vga__putchar(108, color, x + 2, y);
    vga__putchar(108, color, x + 3, y);
    vga__putchar(111, color, x + 4, y);
    vga__putchar(44, color, x + 5, y);
    vga__putchar(32, color, x + 6, y);
    vga__putchar(71, color, x + 7, y);
    vga__putchar(101, color, x + 8, y);
    vga__putchar(99, color, x + 9, y);
    vga__putchar(107, color, x + 10, y);
    vga__putchar(111, color, x + 11, y);
    vga__putchar(33, color, x + 12, y);
    return;
}

void kernel__delay() {
    int64_t i = 0;
    while (i < 5000000) {
    i = i + 1;
    }
    return;
}

void kernel__spinner(int64_t x, int64_t y, uint8_t color) {
    while (1 == 1) {
    vga__putchar(124, color, x, y);
    kernel__delay();
    vga__putchar(47, color, x, y);
    kernel__delay();
    vga__putchar(45, color, x, y);
    kernel__delay();
    vga__putchar(92, color, x, y);
    kernel__delay();
    }
    return;
}

void kmain() {
    cpu__disable_interrupts();
    uint8_t bg = vga__color(vga__WHITE, vga__BLACK);
    vga__clear(bg);
    uint8_t text_color = vga__color(vga__LIGHT_GREEN, vga__BLACK);
    kernel__write_hello(33, 12, text_color);
    uint8_t spinner_color = vga__color(vga__LIGHT_CYAN, vga__BLACK);
    kernel__spinner(47, 12, spinner_color);
    return;
}

